menu:
    Blog: /
    Archive: /archives/
    Weibo: http://weibo.com/sunchongsheng
    GitHub: https://github.com/pinggod
    Rss: /atom.xml

favicon: /favicon.png
logo: /logo.jpg

# index information
info: "It's some information"
# social
social: [
  {t: 'Sina',
   v: 'http://weibo.com'}
]
# Comment
# e.g disqus: seansun
disqus:
duoshuo:
cloudTie:

# Analytics
# google-analytics:
ga: UA-65933410-1 

# Copyright Infomation
startyear: 2015
